version: '3'
services:
  db:
    container_name: rails-api-db
    image: postgres
    env_file: ./rails-api/.env
    volumes:
      - pg-rails-api:/var/lib/postgresql/data
    ports:
      - 5432:5432
  rails-api:
    container_name: rails-api
    build: ./rails-api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails-api:/usr/src/rails-api
    depends_on:
      - db
    ports:
      - 3000:3000
  react-ui:
    container_name: react-ui
    build:
      context: ./react-ui
    depends_on:
      - rails-api
    command: npm start
    volumes:
      - ./react-ui:/usr/src/react-ui
      - ./react-ui/node_modules:/usr/src/react-ui/node_modules
    ports:
      - "4000:4000"
  nginx:
    container_name: nginx
    image: bitnami/nginx:1.10.2-r1
    volumes:
      - ./config/nginx:/bitnami/nginx/conf/vhosts
    depends_on:
      - rails-api
      - react-ui
    environment:
      VIRTUAL_HOST: codekeyz.docker
      VIRTUAL_PORT: 8080
    ports:
      - 8080:8080

volumes:
  pg-rails-api:
